# Generated by Django 4.0 on 2022-07-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
