# Generated by Django 4.0 on 2022-07-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_userbalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBalance',
        ),
    ]
